"""
Input processing module for process data.

This module processes manufacturing process data to generate input features
that correspond to the targets generated by the target_processing module.
"""

__all__ = []
